### ISSUE TITLE
Mention related work

### ISSUE THREAD

**Issue by Ericson2314** [nixpkgs-architecture/simple-package-paths#5]
- https://github.com/triton/triton did the sharding, https://github.com/triton/triton/tree/master/pkgs/all-pkgs in particular.
- What does guix?

**Comment by roberth** [comment]
I see a tree of categories in triton. @Ericson2314 is this a past thing?

**Comment by Ericson2314** [comment]
@roberth yeah I think that is packages that never got moved. They do flatten things.

**Comment by aameen-tulip** [comment]
I used this style for splitting up "unscoped" NPM packages ( e.g. "lodash" -> `unscoped/l/lodash`, "@foo/bar" -> `foo/bar` ).

This resolved my issues with GutHub's web interface.

One notable edge case I encountered was that you need to use `lib.toLower` when creating the substring. Otherwise you'll get inconsistency between Linux and Darwin which is case insensitive with filenames.

https://github.com/aakropotkin/flocoPackages/tree/main/info/unscoped
